=== osandum/gambol-jee/src/main/resources/gambol.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           targetNamespace="http://sandum.net/namespaces/gambol"
           xmlns:g="http://sandum.net/namespaces/gambol"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           jaxb:version="2.1"

           xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
           jaxb:extensionBindingPrefixes="xjc">

    <xs:element name="gambol">
        <xs:complexType>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="section" minOccurs="0" maxOccurs="unbounded" type="g:Section"/>
                </xs:sequence>
                <xs:element name="tournament" type="g:Tournament" />
                <!--xs:element name="fixture" type="g:Fixture" /-->
                <!--xs:element name="gamesheet" type="g:Gamesheet" /-->
            </xs:choice>

            <xs:attribute name="season" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="fixtures">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fixture" minOccurs="0" maxOccurs="unbounded" type="g:Fixture"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="fixture-events" type="g:FixtureEvents" />

    <!-- xs:element name="tournament-source">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="fixtures">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fixture" minOccurs="0" maxOccurs="unbounded" type="g:Fixture"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element -->

    <xs:element name="club">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string" />

                <xs:element name="address" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="lat" type="xs:double" />
                                <xs:attribute name="lon" type="xs:double" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

            <xs:attribute name="country" type="xs:string" />
            <xs:attribute name="slug" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Section">
        <xs:sequence>
            <xs:element name="title" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="tournament" minOccurs="0" maxOccurs="unbounded" type="g:Tournament"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ArenaDef">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="slug" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Used only for tournament source uploads
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="TeamDef">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="side" type="g:FixtureSideRole">
                    <xs:annotation>
                        <xs:documentation>
                            Used only for tournament source uploads
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="club-ref" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Used only for tournament source uploads
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="tournament" type="g:Tournament" />

    <xs:complexType name="Tournament">
        <xs:sequence>
            <xs:element name="title" minOccurs="1" maxOccurs="1" type="xs:string" />
            <xs:element name="details" minOccurs="0" maxOccurs="1" type="xs:anyURI" />
            <xs:element name="fixture" minOccurs="0" maxOccurs="unbounded" type="g:Fixture" />
        </xs:sequence>

        <xs:attribute name="season" type="xs:string" />
        <!-- xs:attribute name="association" type="xs:string" / -->
        <xs:attribute name="source-ref" type="xs:string" use="required" />
        <xs:attribute name="series" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    Used only for query results
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="slug" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    Used only for tournament source uploads
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="arena" type="xs:string"/>
    </xs:complexType>

    <xs:element name="fixture" type="g:Fixture" />

    <xs:complexType name="Fixture">
        <xs:sequence>
            <xs:element name="side" minOccurs="2" maxOccurs="2" type="g:Side" />

            <xs:element name="start-time" minOccurs="1" maxOccurs="1" type="xs:dateTime"/>
            <xs:element name="end-time" minOccurs="1" maxOccurs="1" type="xs:dateTime"/>
            <xs:element name="location" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="result" minOccurs="0" maxOccurs="1" />
            <xs:element name="match-details" minOccurs="0" maxOccurs="1" type="xs:anyURI" />

        </xs:sequence>

        <xs:attribute name="match-number" type="xs:string" />
        <xs:attribute name="source-ref" type="xs:string" />
        <xs:attribute name="tournament-ref" type="xs:string" />
        <xs:attribute name="season" type="xs:string" />
        <xs:attribute name="schedule" type="g:ScheduleStatus" />
        <xs:attribute name="gamesheet" type="g:GamesheetStatus" />
        <xs:attribute name="arena" type="xs:string"/>
    </xs:complexType>
    <!-- /xs:element -->

    <xs:element name="series" type="g:Series" />

    <xs:complexType name="Series">
        <xs:sequence>
            <xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="duration" minOccurs="0" maxOccurs="1" type="xs:nonNegativeInteger"/>
        </xs:sequence>

        <xs:attribute name="slug" type="xs:string" />
    </xs:complexType>
    <!-- /xs:element -->

    <xs:simpleType name="FixtureSideRole" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="home" />
            <xs:enumeration value="away" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GamesheetStatus" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ready" />
            <xs:enumeration value="missing" />
            <xs:enumeration value="failed" />
            <xs:enumeration value="future" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ScheduleStatus" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none" />
            <xs:enumeration value="tentative" />
            <xs:enumeration value="confirmed" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GameOffense" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DIVE" />
            <xs:enumeration value="ABUSE" />
            <xs:enumeration value="TAUNT" />
            <xs:enumeration value="AU-MI" />
            <xs:enumeration value="AU-GM" />
            <xs:enumeration value="BD-CK" />

            <xs:enumeration value="TRIP" />
            <xs:enumeration value="KICK" />
            <xs:enumeration value="SLASH" />
            <xs:enumeration value="HOOK" />
            <xs:enumeration value="HOLD" />
            <xs:enumeration value="CLIP" />
            <xs:enumeration value="BUTT" />
            <xs:enumeration value="SPEAR" />
            <xs:enumeration value="CROSS" />
            <xs:enumeration value="BENCH" />
            <xs:enumeration value="BOARD" />
            <xs:enumeration value="CHARG" />
            <xs:enumeration value="HI-ST" />
            <xs:enumeration value="HO-ST" />
            <xs:enumeration value="BR-ST" />
            <xs:enumeration value="THR-S" />
            <xs:enumeration value="HEAD" />
            <xs:enumeration value="ELBOW" />
            <xs:enumeration value="FIST" />
            <xs:enumeration value="KNEE" />
            <xs:enumeration value="INTRF" />
            <xs:enumeration value="ROUGH" />
            <xs:enumeration value="DELAY" />
            <xs:enumeration value="REFUS" />
            <xs:enumeration value="EMBEL" />
            <xs:enumeration value="DE-GK" />            
            <xs:enumeration value="UN-SP" />
            <xs:enumeration value="BD-CK" />
            <xs:enumeration value="CHE-B" />
            <xs:enumeration value="CHE-H" />
            <xs:enumeration value="IL-ST" />
            <xs:enumeration value="IL-EQ" />
            <xs:enumeration value="TOO-M" />
            <xs:enumeration value="P-OUT" />

            <xs:enumeration value="GA-MI" />
            <xs:enumeration value="MISC" />
            <xs:enumeration value="MATCH" />

            <xs:enumeration value="PEN-S" />
            <xs:enumeration value="OTHER" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GameSituation" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="EQ" />
            <xs:enumeration value="PP1" />
            <xs:enumeration value="PP2" />
            <xs:enumeration value="SH1" />
            <xs:enumeration value="SH2" />
            <xs:enumeration value="GWS" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GamePeriod" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="P1" />
            <xs:enumeration value="P2" />
            <xs:enumeration value="P3" />
            <xs:enumeration value="OVT" />
            <xs:enumeration value="GWS" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="FixtureEvents">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="goal" type="g:GoalEvent" />
            <xs:element name="penalty" type="g:PenaltyEvent" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="Side">
        <xs:sequence>
            <xs:element name="team" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="club-ref" type="xs:string" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="score" minOccurs="0" maxOccurs="1" type="xs:nonNegativeInteger" />
        </xs:sequence>

        <xs:attribute name="role" type="g:FixtureSideRole" />
    </xs:complexType>

    <xs:element name="gamesheet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tournament" minOccurs="0" maxOccurs="1" type="g:Tournament"/>
                <xs:element name="arena" minOccurs="0" maxOccurs="1" type="g:ArenaDef"/>
                <xs:element name="start-time" minOccurs="0" maxOccurs="1" type="xs:dateTime"/>
                <xs:element name="spectators" minOccurs="0" maxOccurs="1" type="xs:nonNegativeInteger"/>
                <xs:element name="game-period" minOccurs="0" maxOccurs="unbounded" type="g:PeriodSummary"/>
                <xs:element name="team" minOccurs="0" maxOccurs="2" type="g:TeamDef"/>
                <xs:element name="roster" minOccurs="2" maxOccurs="2" type="g:Roster" />
                <xs:element name="events" type="g:FixtureEvents" />
            </xs:sequence>

            <xs:attribute name="source-ref" type="xs:string" use="required" />
            <xs:attribute name="match-number" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Roster">
        <xs:sequence>
            <xs:element name="official" minOccurs="0" maxOccurs="unbounded" type="g:Official" />
            <xs:element name="player" minOccurs="0" maxOccurs="unbounded" type="g:Player" />
        </xs:sequence>

        <xs:attribute name="side" type="g:FixtureSideRole" />
    </xs:complexType>

    <xs:complexType name="Signup">
        <xs:attribute name="season" type="xs:string" />
        <xs:attribute name="series" type="xs:string" />
        <xs:attribute name="club-ref" type="xs:string" />
        <xs:attribute name="person-ref" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="PeriodSummary">
        <xs:sequence>
            <xs:element name="goals" type="g:HomeAwayScore" />
            <xs:element name="attempts" type="g:HomeAwayScore" />
            <xs:element name="penalty-minutes"  type="g:HomeAwayScore" />
        </xs:sequence>

        <xs:attribute name="period" type="g:GamePeriod" />
    </xs:complexType>

    <xs:complexType name="HomeAwayScore">
        <xs:attribute name="home" type="xs:integer" />
        <xs:attribute name="away" type="xs:integer" />
    </xs:complexType>

    <xs:element name="person" type="g:Person" />

    <xs:complexType name="Person">
        <xs:sequence>
            <xs:element name="first-names" type="xs:string" />
            <xs:element name="last-name" minOccurs="0" type="xs:string" />
            <xs:element name="details" minOccurs="0" maxOccurs="1" type="xs:anyURI" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Player">
        <xs:complexContent>
            <xs:extension base="g:Person">
                <xs:attribute name="number" type="xs:positiveInteger" />
                <xs:attribute name="line" type="xs:string" />
                <xs:attribute name="pos" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Official">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="role" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="PlayerRef">
        <xs:attribute name="number" type="xs:positiveInteger" />
    </xs:complexType>

    <xs:complexType name="Event">
        <xs:sequence>
            <xs:element name="time" type="xs:string" />
            <xs:element name="player" type="g:PlayerRef" />
            <xs:element name="fixture" minOccurs="0" maxOccurs="1" type="xs:anyURI" />
        </xs:sequence>

        <xs:attribute name="side" type="g:FixtureSideRole" />
    </xs:complexType>

    <xs:complexType name="GoalEvent">
        <xs:complexContent>
            <xs:extension base="g:Event">
                <xs:sequence>
                    <xs:element name="assist" type="g:PlayerRef" minOccurs="0" maxOccurs="3" />
                    <xs:element name="participation" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="positive" type="g:Participants" />
                                <xs:element name="negative" type="g:Participants" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>

                <xs:attribute name="game-situation" type="g:GameSituation" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Participants">
        <xs:sequence>
            <xs:element name="player" type="g:PlayerRef" minOccurs="0" maxOccurs="6" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PenaltyEvent">
        <xs:complexContent>
            <xs:extension base="g:Event">
                <xs:sequence>
                    <xs:element name="minutes" type="xs:nonNegativeInteger" />
                    <xs:element name="offense" type="g:GameOffense" />
                    <xs:element name="start-time" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="end-time" type="xs:string" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


</xs:schema>

=== osandum/gambol-jee/src/test/resources/sample/game-31811.xml
<?xml version="1.0" encoding="utf-8"?>
<gambol xmlns="http://sandum.net/namespaces/gambol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sandum.net/namespaces/gambol file:/home/osa/KSF/openshift/gambol-docs/src/main/resources/gambol.xsd">
  <gamesheet source-ref="DIU:1045:31811">
    <roster side="home">
      <player pos="GK" number="30">
        <first-names>Peter</first-names>
        <last-name>Becher Nielsen</last-name>
      </player>
      <player pos="GK" number="79">
        <first-names>Emil</first-names>
        <last-name>Gransøe</last-name>
      </player>
      <player line="1" pos="CE" number="32">
        <first-names>Jonas</first-names>
        <last-name>Veiby</last-name>
      </player>
      <player line="1" pos="LD" number="71">
        <first-names>Daniel</first-names>
        <last-name>Baastrup-Andersen</last-name>
      </player>
      <player line="1" pos="LW" number="29">
        <first-names>Christopher Skovgaard</first-names>
        <last-name>Nielsen</last-name>
      </player>
      <player line="1" pos="RD" number="12">
        <first-names>Stefan</first-names>
        <last-name>Stokholm</last-name>
      </player>
      <player line="1" pos="RW" number="61">
        <first-names>Emil</first-names>
        <last-name>Grandal</last-name>
      </player>
      <player line="2" pos="CE" number="23">
        <first-names>Jeppe</first-names>
        <last-name>Klitgaard</last-name>
      </player>
      <player line="2" pos="LD" number="50">
        <first-names>Mikkel</first-names>
        <last-name>Svenson</last-name>
      </player>
      <player line="2" pos="LW" number="25">
        <first-names>Mads</first-names>
        <last-name>Crone</last-name>
      </player>
      <player line="2" pos="RD" number="8">
        <first-names>Carl Gustav</first-names>
        <last-name>Schultz</last-name>
      </player>
      <player line="2" pos="RW" number="24">
        <first-names>Rasmus</first-names>
        <last-name>Klokholm</last-name>
      </player>
      <player line="3" pos="CE" number="26">
        <first-names>Frederik</first-names>
        <last-name>Christensen</last-name>
      </player>
      <player line="3" pos="LD" number="81">
        <first-names>Oliver Jerichow</first-names>
        <last-name>Mailund</last-name>
      </player>
      <player line="3" pos="LW" number="17">
        <first-names>Magnus</first-names>
        <last-name>Ferslew</last-name>
      </player>
      <player line="3" pos="RW" number="10">
        <first-names>Jesper</first-names>
        <last-name>malle</last-name>
      </player>
      <player line="4" pos="LW" number="9">
        <first-names>Marcus Møller</first-names>
        <last-name>Winther</last-name>
      </player>
    </roster>
    <roster side="away">
      <player pos="GK" number="31">
        <first-names>Jacob B.</first-names>
        <last-name>Jensen</last-name>
      </player>
      <player pos="GK" number="1">
        <first-names>Jesper Wulff</first-names>
        <last-name>Pedersen</last-name>
      </player>
      <player line="1" pos="CE" number="9">
        <first-names>Alexander Brinkman</first-names>
        <last-name>Andersen</last-name>
      </player>
      <player line="1" pos="LD" number="4">
        <first-names>Mathias</first-names>
        <last-name>Pehrson</last-name>
      </player>
      <player line="1" pos="LW" number="3">
        <first-names>Emil</first-names>
        <last-name>Borup</last-name>
      </player>
      <player line="1" pos="RD" number="18">
        <first-names>Lasse Bo</first-names>
        <last-name>Knudsen</last-name>
      </player>
      <player line="1" pos="RW" number="16">
        <first-names>Oliver</first-names>
        <last-name>Anker Christensen</last-name>
      </player>
      <player line="2" pos="CE" number="6">
        <first-names>Tobias Sand</first-names>
        <last-name>Christensen</last-name>
      </player>
      <player line="2" pos="LD" number="17">
        <first-names>Søren</first-names>
        <last-name>Vestergaard</last-name>
      </player>
      <player line="2" pos="LW" number="14">
        <first-names>Sebastian</first-names>
        <last-name>Ehlers</last-name>
      </player>
      <player line="2" pos="RD" number="12">
        <first-names>Mike</first-names>
        <last-name>Lindstrøm</last-name>
      </player>
      <player line="2" pos="RW" number="19">
        <first-names>Matias</first-names>
        <last-name>Posio</last-name>
      </player>
      <player line="3" pos="RD" number="5">
        <first-names>Oliver Gatz</first-names>
        <last-name>Nielsen</last-name>
      </player>
      <player line="3" pos="RW" number="21">
        <first-names>Emil</first-names>
        <last-name>Marcussen</last-name>
      </player>
    </roster>
    <events>
      <goal side="home" game-situation="EQ">
        <time>00:06</time>
        <player number="61"/>
        <assist number="32"/>
      </goal>
      <penalty side="home">
        <time>01:16</time>
        <player number="12"/>
        <minutes>2</minutes>
        <offense>CROSS</offense>
        <end-time>03:16</end-time>
      </penalty>
      <penalty side="home">
        <time>07:36</time>
        <player number="50"/>
        <minutes>2</minutes>
        <offense>BOARD</offense>
        <end-time>09:36</end-time>
      </penalty>
      <penalty side="away">
        <time>13:59</time>
        <player number="3"/>
        <minutes>2</minutes>
        <offense>HI-ST</offense>
        <end-time>15:59</end-time>
      </penalty>
      <penalty side="home">
        <time>26:09</time>
        <player number="10"/>
        <minutes>2</minutes>
        <offense>INTRF</offense>
        <end-time>28:09</end-time>
      </penalty>
      <penalty side="home">
        <time>27:48</time>
        <player number="50"/>
        <minutes>2</minutes>
        <offense>UN-SP</offense>
        <end-time>29:48</end-time>
      </penalty>
      <goal side="away" game-situation="PP1">
        <time>29:42</time>
        <player number="17"/>
        <assist number="16"/>
        <assist number="21"/>
      </goal>
      <penalty side="away">
        <time>34:34</time>
        <player number="12"/>
        <minutes>2</minutes>
        <offense>DELAY</offense>
        <end-time>36:34</end-time>
      </penalty>
      <goal side="away" game-situation="EQ">
        <time>47:32</time>
        <player number="16"/>
        <assist number="21"/>
      </goal>
      <penalty side="home">
        <time>49:28</time>
        <player number="25"/>
        <minutes>2</minutes>
        <offense>ELBOW</offense>
        <end-time>51:28</end-time>
      </penalty>
      <penalty side="away">
        <time>53:12</time>
        <player number="21"/>
        <minutes>2</minutes>
        <offense>INTRF</offense>
        <end-time>55:12</end-time>
      </penalty>
      <goal side="home" game-situation="PP1">
        <time>54:59</time>
        <player number="12"/>
        <assist number="61"/>
        <assist number="8"/>
      </goal>
      <goal side="home" game-situation="GWS">
        <time>65:00</time>
        <player number="61"/>
      </goal>
    </events>
  </gamesheet>
</gambol>
